name: "Deploy Proxy Target Permit2"

env:
  API_KEY_ARBISCAN: ${{ secrets.API_KEY_ARBISCAN }}
  API_KEY_BSCSCAN: ${{ secrets.API_KEY_BSCSCAN }}
  API_KEY_ETHERSCAN: ${{ secrets.API_KEY_ETHERSCAN }}
  API_KEY_GNOSISSCAN: ${{ secrets.API_KEY_GNOSISSCAN }}
  API_KEY_INFURA: ${{ secrets.API_KEY_INFURA }}
  API_KEY_OPTIMISTIC_ETHERSCAN: ${{ secrets.API_KEY_OPTIMISTIC_ETHERSCAN }}
  API_KEY_POLYGONSCAN: ${{ secrets.API_KEY_POLYGONSCAN }}
  API_KEY_SNOWTRACE: ${{ secrets.API_KEY_SNOWTRACE }}
  FOUNDRY_PROFILE: "optimized"
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      chain:
        default: "goerli"
        description: "Chain name as defined in the Foundry config."
        required: false
      permit2:
        default: "0x000000000022D473030F116dDEE9F6B43aC78BA3"
        description: "The permit2 address."
        required: false

jobs:
  deploy-proxy-target-permit2:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Deploy the SablierV2ProxyTargetPermit2 contract"
        run: >-
          forge script script/DeployProxyTargetPermit2.s.sol
          --broadcast
          --rpc-url "${{ inputs.chain }}"
          --sig "run(address)"
          --verify
          -vvvv
          "${{ inputs.permit2 }}"

      - name: "Add workflow summary"
        run: |
          echo "## Result" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Done" >> $GITHUB_STEP_SUMMARY
