name: "List in Archive"

env:
  API_KEY_ARBISCAN: ${{ secrets.API_KEY_ARBISCAN }}
  API_KEY_BSCSCAN: ${{ secrets.API_KEY_BSCSCAN }}
  API_KEY_ETHERSCAN: ${{ secrets.API_KEY_ETHERSCAN }}
  API_KEY_GNOSISSCAN: ${{ secrets.API_KEY_GNOSISSCAN }}
  API_KEY_INFURA: ${{ secrets.API_KEY_INFURA }}
  API_KEY_OPTIMISTIC_ETHERSCAN: ${{ secrets.API_KEY_OPTIMISTIC_ETHERSCAN }}
  API_KEY_POLYGONSCAN: ${{ secrets.API_KEY_POLYGONSCAN }}
  API_KEY_SNOWTRACE: ${{ secrets.API_KEY_SNOWTRACE }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      address:
        description: "Contract to list in the archive."
        required: true
      archive:
        description: "Address of the archive contract."
        required: true
      chain:
        default: "goerli"
        description: "Chain name as defined in the Foundry config."
        required: false

jobs:
  list-in-archive:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "List the provided address in the archive"
        run: >-
          forge script script/ListInArchive.s.sol
          --broadcast
          --rpc-url "${{ inputs.chain }}"
          --sig "run(address,address)"
          -vvvv
          "${{ inputs.archive }}"
          "${{ inputs.address }}"

      - name: "Add workflow summary"
        run: |
          echo "## Result" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Done" >> $GITHUB_STEP_SUMMARY
